/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function BaguetteSimple(props) {
  const { nodes, materials } = useGLTF('/BaguetteSimple.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Baguette.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/BaguetteSimple.gltf')

export default BaguetteSimple
