/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Color } from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ModelDos.gltf')
  // Créez un objet Color avec la couleur souhaitée (rouge dans cet exemple)
  const newColor = new Color(props.colorPP)
  //materials['Paper old'].color.set(props.DosColor)
  materials['Paper old'].color = newColor
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Dos.geometry} material={materials['Paper old']} position={[0, -2.1, 0]} />
    </group>
  )
}

useGLTF.preload('/ModelDos.gltf')
